-- ============================================================
-- 블로그 글 줄표(—, –, ' - ') 제거
-- 줄 단위 replace() 라서 문장이 이미 바뀌었으면 해당 줄은 아무것도 바꾸지 않습니다.
-- Supabase SQL Editor 에서 전체 실행하세요.
-- ============================================================

BEGIN;

UPDATE blog_posts SET title_ko = replace(title_ko, $o$여백이 두려웠던 시절 — 빈 공간은 비어 있는 게 아니에요$o$, $n$여백이 두려웠던 시절, 빈 공간은 비어 있는 게 아니었어요$n$) WHERE id = 'design-whitespace';
UPDATE blog_posts SET title_en = replace(title_en, $o$When I Was Afraid of Whitespace — Empty Space Isn't Really Empty$o$, $n$I Used to Be Afraid of Whitespace. Empty Space Isn't Really Empty$n$) WHERE id = 'design-whitespace';
UPDATE blog_posts SET content_ko = replace(content_ko, $o$처음 UI를 만들기 시작했을 때, 화면에 빈 공간이 보이면 불안했어요. '여기에 뭘 더 넣어야 하지?' 하는 생각이 자동으로 들었거든요. 카드 사이의 간격이 넓으면 '너무 허전한 거 아닌가', 섹션 아래에 여백이 크면 '콘텐츠가 부족해 보이지 않나' — 그런 고민을 계속 했어요.$o$, $n$처음 UI를 만들기 시작했을 때, 화면에 빈 공간이 보이면 불안했어요. '여기에 뭘 더 넣어야 하지?' 하는 생각이 자동으로 들었거든요. 카드 사이의 간격이 넓으면 '너무 허전한 거 아닌가', 섹션 아래에 여백이 크면 '콘텐츠가 부족해 보이지 않나' 하는 고민을 계속 했어요.$n$) WHERE id = 'design-whitespace';
UPDATE blog_posts SET content_ko = replace(content_ko, $o$**여백은 일정한 단위로 움직여야 해요.** 저는 보통 4px 또는 8px을 기본 단위로 쓰는데, 모든 간격이 이 배수로 떨어지게 해요. 12px, 16px, 24px, 32px, 48px, 64px — 이렇게요. 규칙 없이 '이 정도면 되겠지' 하고 넣으면 화면 전체에서 미묘한 불일치가 쌓이거든요. 사용자가 의식하진 못하지만 '뭔가 정돈 안 된 느낌'을 받게 돼요.$o$, $n$**여백은 일정한 단위로 움직여야 해요.** 저는 보통 4px 또는 8px을 기본 단위로 쓰는데, 모든 간격이 이 배수로 떨어지게 해요. 12px, 16px, 24px, 32px, 48px, 64px처럼요. 규칙 없이 '이 정도면 되겠지' 하고 넣으면 화면 전체에서 미묘한 불일치가 쌓이거든요. 사용자가 의식하진 못하지만 '뭔가 정돈 안 된 느낌'을 받게 돼요.$n$) WHERE id = 'design-whitespace';
UPDATE blog_posts SET content_en = replace(content_en, $o$**The closer the relationship between elements, the tighter the spacing should be.** Between a label and its input field, 4-8px is plenty. But between one input group and the next, you need at least 24px, and between sections, 48-80px. In Gestalt psychology this is called the "principle of proximity" — fancy name, simple idea. Things close together seem related; things far apart seem separate.$o$, $n$**The closer the relationship between elements, the tighter the spacing should be.** Between a label and its input field, 4-8px is plenty. But between one input group and the next, you need at least 24px, and between sections, 48-80px. In Gestalt psychology this is called the "principle of proximity." Fancy name, simple idea. Things close together seem related; things far apart seem separate.$n$) WHERE id = 'design-whitespace';
UPDATE blog_posts SET content_en = replace(content_en, $o$Whitespace doesn't exist because there's not enough content — it's deliberately created so that content can be seen properly. "Filling the screen" and "designing the screen" are completely different tasks. After I stopped being afraid of empty space, the feel of everything I built changed dramatically.$o$, $n$Whitespace doesn't exist because there's not enough content. It's deliberately created so that content can be seen properly. "Filling the screen" and "designing the screen" are completely different tasks. After I stopped being afraid of empty space, the feel of everything I built changed dramatically.$n$) WHERE id = 'design-whitespace';
UPDATE blog_posts SET content_en = replace(content_en, $o$Even now, the first thing I do when building a screen isn't deciding "what to put here" — it's deciding "what *not* to put here."$o$, $n$Even now, the first thing I do when building a screen isn't deciding "what to put here." It's deciding "what *not* to put here."$n$) WHERE id = 'design-whitespace';
UPDATE blog_posts SET content_ko = replace(content_ko, $o$Keyrke 프로젝트에서 디자인 시스템을 만들 때, 가장 처음 막힌 게 색상이었어요. '메인 컬러를 뭘로 하지?' 같은 거창한 고민이 아니라, 훨씬 실무적인 문제였어요. 버튼의 hover 색은 뭘로 할 건지, disabled 상태는 어떤 회색을 쓸 건지, 에러 메시지의 빨간색은 배경이 어두울 때도 같은 값을 쓸 건지 — 이런 것들이요.$o$, $n$Keyrke 프로젝트에서 디자인 시스템을 만들 때, 가장 처음 막힌 게 색상이었어요. '메인 컬러를 뭘로 하지?' 같은 거창한 고민이 아니라, 훨씬 실무적인 문제였어요. 버튼의 hover 색은 뭘로 할 건지, disabled 상태는 어떤 회색을 쓸 건지, 에러 메시지의 빨간색은 배경이 어두울 때도 같은 값을 쓸 건지 같은 것들이요.$n$) WHERE id = 'design-color-system';
UPDATE blog_posts SET content_ko = replace(content_ko, $o$**gray도 같은 방식으로 나눴어요.** 사실 UI에서 가장 많이 쓰이는 건 gray거든요. 배경, 보더, 비활성 텍스트, 구분선, placeholder — 전부 gray의 변형이에요. gray를 체계 없이 쓰면 화면이 탁해 보이고, 체계적으로 쓰면 깔끔해 보여요. 차이는 미세한데, 느낌은 확연히 달라요.$o$, $n$**gray도 같은 방식으로 나눴어요.** 사실 UI에서 가장 많이 쓰이는 건 gray거든요. 배경, 보더, 비활성 텍스트, 구분선, placeholder가 전부 gray의 변형이에요. gray를 체계 없이 쓰면 화면이 탁해 보이고, 체계적으로 쓰면 깔끔해 보여요. 차이는 미세한데, 느낌은 확연히 달라요.$n$) WHERE id = 'design-color-system';
UPDATE blog_posts SET content_en = replace(content_en, $o$When I was building the design system for the Keyrke project, the very first thing I got stuck on was color. It wasn't a grand question like "What should our primary color be?" — it was far more practical. What color should a button's hover state be? Which gray goes on a disabled state? Should the red for error messages stay the same value on a dark background? Those kinds of things.$o$, $n$When I was building the design system for the Keyrke project, the very first thing I got stuck on was color. It wasn't a grand question like "What should our primary color be?" It was far more practical. What color should a button's hover state be? Which gray goes on a disabled state? Should the red for error messages stay the same value on a dark background? Those kinds of things.$n$) WHERE id = 'design-color-system';
UPDATE blog_posts SET content_en = replace(content_en, $o$At first, I picked colors by eye every time — "this looks about right." The result was subtly different grays on every screen, and the same "disabled" state showing up as opacity 0.4 on one screen and 0.5 on another. When I was working alone, I could keep things consistent by feel. The moment a teammate started using the same components, it all fell apart.$o$, $n$At first, I picked colors by eye every time, going with whatever "looked about right." The result was subtly different grays on every screen, and the same "disabled" state showing up as opacity 0.4 on one screen and 0.5 on another. When I was working alone, I could keep things consistent by feel. The moment a teammate started using the same components, it all fell apart.$n$) WHERE id = 'design-color-system';
UPDATE blog_posts SET content_en = replace(content_en, $o$**I applied the same approach to gray.** Gray is actually the most-used color in any UI. Backgrounds, borders, disabled text, dividers, placeholders — they're all variations of gray. When gray is used without a system the screen looks muddy; when it's used systematically, it looks clean. The differences are subtle, but the impression is strikingly different.$o$, $n$**I applied the same approach to gray.** Gray is actually the most-used color in any UI. Backgrounds, borders, disabled text, dividers, and placeholders are all variations of gray. When gray is used without a system the screen looks muddy; when it's used systematically, it looks clean. The differences are subtle, but the impression is strikingly different.$n$) WHERE id = 'design-color-system';
UPDATE blog_posts SET content_en = replace(content_en, $o$**Dark mode colors were mapped separately.** If gray-100 is the background in light mode, then gray-900 becomes the background in dark mode. Rather than simply inverting the scale, I built a light/dark mapping table for each role — background, surface, text, border. This process made it crystal clear that "color is a role, not a value."$o$, $n$**Dark mode colors were mapped separately.** If gray-100 is the background in light mode, then gray-900 becomes the background in dark mode. Rather than simply inverting the scale, I built a light/dark mapping table for each role (background, surface, text, border). This process made it crystal clear that "color is a role, not a value."$n$) WHERE id = 'design-color-system';
UPDATE blog_posts SET title_ko = replace(title_ko, $o$애니메이션을 넣기 전에 물어봐야 할 한 가지 — '이걸 빼면 뭘 잃는가'$o$, $n$애니메이션을 넣기 전에 '이걸 빼면 뭘 잃지?'부터 물어봐요$n$) WHERE id = 'design-animation-philosophy';
UPDATE blog_posts SET title_en = replace(title_en, $o$One Question Before Adding Animation — What Do We Lose Without It?$o$, $n$Before Adding Animation, Ask What You'd Lose Without It$n$) WHERE id = 'design-animation-philosophy';
UPDATE blog_posts SET content_ko = replace(content_ko, $o$이 포트폴리오 사이트의 히어로 섹션을 만들면서 꽤 긴 시간을 애니메이션에 썼어요. 얼굴 이미지가 파티클로 분해되고, 인사말로 모였다가 흩어지고, 텍스트로 다시 모이고, 마지막에 별처럼 날아가는 — 꽤 복잡한 스크롤 기반 애니메이션이에요.$o$, $n$이 포트폴리오 사이트의 히어로 섹션을 만들면서 꽤 긴 시간을 애니메이션에 썼어요. 얼굴 이미지가 파티클로 분해되고, 인사말로 모였다가 흩어지고, 텍스트로 다시 모이고, 마지막에 별처럼 날아가는, 꽤 복잡한 스크롤 기반 애니메이션이에요.$n$) WHERE id = 'design-animation-philosophy';
UPDATE blog_posts SET content_ko = replace(content_ko, $o$하나는 **기능적 애니메이션**이에요. 페이지 전환, 모달 열기/닫기, 데이터 로딩, 토스트 알림 — 이런 것들에 붙는 애니메이션이요. 이건 '장식'이 아니라 '정보'에 가까워요. 모달이 아래에서 올라오면 사용자는 '새로운 레이어가 위에 생겼구나'라고 직감적으로 이해하거든요. 이런 애니메이션이 없으면 화면이 '갑자기' 바뀌는 느낌이 들어서 사용자가 현재 상태를 파악하는 데 인지 비용이 들어요.$o$, $n$하나는 **기능적 애니메이션**이에요. 페이지 전환, 모달 열기/닫기, 데이터 로딩, 토스트 알림 같은 것들에 붙는 애니메이션이요. 이건 '장식'이 아니라 '정보'에 가까워요. 모달이 아래에서 올라오면 사용자는 '새로운 레이어가 위에 생겼구나'라고 직감적으로 이해하거든요. 이런 애니메이션이 없으면 화면이 '갑자기' 바뀌는 느낌이 들어서 사용자가 현재 상태를 파악하는 데 인지 비용이 들어요.$n$) WHERE id = 'design-animation-philosophy';
UPDATE blog_posts SET content_en = replace(content_en, $o$While building the hero section of this portfolio site, I spent a considerable amount of time on animation. The face image breaks apart into particles, gathers into a greeting, scatters, reassembles into text, and finally flies away like stars — it's a fairly complex scroll-driven animation.$o$, $n$While building the hero section of this portfolio site, I spent a considerable amount of time on animation. The face image breaks apart into particles, gathers into a greeting, scatters, reassembles into text, and finally flies away like stars. It's a fairly complex scroll-driven animation.$n$) WHERE id = 'design-animation-philosophy';
UPDATE blog_posts SET content_en = replace(content_en, $o$The first is **functional animation**. Page transitions, modal open/close, data loading, toast notifications — animations attached to these kinds of interactions. These aren't "decoration" but closer to "information." When a modal slides up from the bottom, users intuitively understand that a new layer has appeared on top. Without these animations, the screen feels like it changes "abruptly," and users have to spend cognitive effort figuring out the current state.$o$, $n$The first is **functional animation**, the kind attached to page transitions, modal open/close, data loading, and toast notifications. These aren't "decoration" but closer to "information." When a modal slides up from the bottom, users intuitively understand that a new layer has appeared on top. Without these animations, the screen feels like it changes "abruptly," and users have to spend cognitive effort figuring out the current state.$n$) WHERE id = 'design-animation-philosophy';
UPDATE blog_posts SET content_en = replace(content_en, $o$**You need to consider motion-sensitive users.** If the prefers-reduced-motion media query is active, animations should be reduced or replaced with static alternatives. This isn't optional — it's an accessibility baseline.$o$, $n$**You need to consider motion-sensitive users.** If the prefers-reduced-motion media query is active, animations should be reduced or replaced with static alternatives. This isn't optional. It's an accessibility baseline.$n$) WHERE id = 'design-animation-philosophy';
UPDATE blog_posts SET title_ko = replace(title_ko, $o$디자이너에서 개발자로 — UI를 바라보는 시선이 달라진 순간$o$, $n$디자이너에서 개발자로, UI를 보는 시선이 달라진 순간$n$) WHERE id = 'design-ui-without-designer';
UPDATE blog_posts SET title_en = replace(title_en, $o$From Designer to Developer — When My Perspective on UI Changed$o$, $n$How Moving from Design to Development Changed the Way I See UI$n$) WHERE id = 'design-ui-without-designer';
UPDATE blog_posts SET content_ko = replace(content_ko, $o$**상태(state)라는 개념이 없었어요.** 디자인할 때는 '완성된 화면'만 그렸거든요. 버튼은 항상 활성 상태, 리스트에는 항상 데이터가 있고, 에러는 별도 시안으로 따로 만들었어요. 그런데 개발을 시작하니까 — 로딩 중일 때, 데이터가 없을 때, 에러가 났을 때, 권한이 없을 때 — 한 컴포넌트가 가질 수 있는 상태가 너무 많았어요. 디자인 시안에는 2~3개 화면이지만, 실제 코드에서는 10가지 이상의 경우를 처리해야 했어요.$o$, $n$**상태(state)라는 개념이 없었어요.** 디자인할 때는 '완성된 화면'만 그렸거든요. 버튼은 항상 활성 상태, 리스트에는 항상 데이터가 있고, 에러는 별도 시안으로 따로 만들었어요. 그런데 개발을 시작하니까 로딩 중일 때, 데이터가 없을 때, 에러가 났을 때, 권한이 없을 때처럼 한 컴포넌트가 가질 수 있는 상태가 너무 많았어요. 디자인 시안에는 2~3개 화면이지만, 실제 코드에서는 10가지 이상의 경우를 처리해야 했어요.$n$) WHERE id = 'design-ui-without-designer';
UPDATE blog_posts SET content_ko = replace(content_ko, $o$**반복 가능한 구조의 중요성을 몰랐어요.** 디자이너일 때는 화면마다 조금씩 다르게 만들어도 괜찮았어요. 이 카드는 패딩 16px, 저 카드는 20px — '이 화면에서는 이게 더 예뻐 보이니까'라는 이유로요. 그런데 컴포넌트로 구현할 때 이런 미세한 차이는 재사용을 어렵게 만들고, 결국 비슷한 컴포넌트가 여러 개 생기는 원인이 됐어요.$o$, $n$**반복 가능한 구조의 중요성을 몰랐어요.** 디자이너일 때는 화면마다 조금씩 다르게 만들어도 괜찮았어요. 이 카드는 패딩 16px, 저 카드는 20px. '이 화면에서는 이게 더 예뻐 보이니까'라는 이유로요. 그런데 컴포넌트로 구현할 때 이런 미세한 차이는 재사용을 어렵게 만들고, 결국 비슷한 컴포넌트가 여러 개 생기는 원인이 됐어요.$n$) WHERE id = 'design-ui-without-designer';
UPDATE blog_posts SET content_ko = replace(content_ko, $o$**2. 상태를 전부 정의해요.** default, hover, loading, empty, error, disabled — 한 컴포넌트의 모든 상태를 시안 단계에서 만들어요.$o$, $n$**2. 상태를 전부 정의해요.** default, hover, loading, empty, error, disabled까지 한 컴포넌트의 모든 상태를 시안 단계에서 만들어요.$n$) WHERE id = 'design-ui-without-designer';
UPDATE blog_posts SET content_en = replace(content_en, $o$**I had no concept of state.** When designing, I only drew "finished screens." Buttons were always active, lists always had data, and errors were separate mockups. But once I started coding — loading states, empty states, error states, unauthorized states — a single component could have so many states. A design file had 2-3 screens, but the actual code needed to handle 10+ cases.$o$, $n$**I had no concept of state.** When designing, I only drew "finished screens." Buttons were always active, lists always had data, and errors were separate mockups. But once I started coding, a single component turned out to have loading states, empty states, error states, unauthorized states, and more. A design file had 2-3 screens, but the actual code needed to handle 10+ cases.$n$) WHERE id = 'design-ui-without-designer';
UPDATE blog_posts SET content_en = replace(content_en, $o$**I didn't understand the importance of repeatable structure.** As a designer, making things slightly different per screen was fine. This card has 16px padding, that card has 20px — "because this looks better on this screen." But when implementing as components, these subtle differences made reuse difficult and led to multiple similar components proliferating.$o$, $n$**I didn't understand the importance of repeatable structure.** As a designer, making things slightly different per screen was fine. This card has 16px padding, that card has 20px, "because this looks better on this screen." But when implementing as components, these subtle differences made reuse difficult and led to multiple similar components proliferating.$n$) WHERE id = 'design-ui-without-designer';
UPDATE blog_posts SET content_en = replace(content_en, $o$**2. Define all states.** Default, hover, loading, empty, error, disabled — I create all states of a component during the mockup phase.$o$, $n$**2. Define all states.** I create every state of a component (default, hover, loading, empty, error, disabled) during the mockup phase.$n$) WHERE id = 'design-ui-without-designer';
UPDATE blog_posts SET content_ko = replace(content_ko, $o$**정보의 순서를 행동 기준으로 재배치했어요.** 사용자가 구매 결정을 내리는 데 필요한 정보 순서로 — 가격 → 옵션 → 주요 특징 → 상세 설명 → 리뷰. '상세 설명'은 예쁘지만, 실제로 그걸 끝까지 읽는 사용자는 많지 않아요.$o$, $n$**정보의 순서를 행동 기준으로 재배치했어요.** 사용자가 구매 결정을 내리는 데 필요한 순서대로 가격 → 옵션 → 주요 특징 → 상세 설명 → 리뷰로 바꿨어요. '상세 설명'은 예쁘지만, 실제로 그걸 끝까지 읽는 사용자는 많지 않아요.$n$) WHERE id = 'design-user-action';
UPDATE blog_posts SET content_en = replace(content_en, $o$For a product detail page, the user's action is "Buy" or "Select Options." That means the path toward that action needs to be the clearest thing on the page. Information exists to support the action — it's not the goal itself.$o$, $n$For a product detail page, the user's action is "Buy" or "Select Options." That means the path toward that action needs to be the clearest thing on the page. Information exists to support the action. It isn't the goal itself.$n$) WHERE id = 'design-user-action';
UPDATE blog_posts SET content_en = replace(content_en, $o$**I reordered information based on the action.** In the order users need to make a purchase decision — price, options, key features, detailed description, reviews. The "detailed description" section looks nice, but in reality, not many users read it all the way through.$o$, $n$**I reordered information based on the action.** I put it in the order users need to make a purchase decision: price, options, key features, detailed description, then reviews. The "detailed description" section looks nice, but in reality, not many users read it all the way through.$n$) WHERE id = 'design-user-action';
UPDATE blog_posts SET content_ko = replace(content_ko, $o$만들면서 새로 쓴 코드, 고쳐야 했던 설계, 모바일에서 이상하게 보여서 다시 손댄 UI들 — 이게 다 실제로 겪은 문제들이에요.$o$, $n$만들면서 새로 쓴 코드, 고쳐야 했던 설계, 모바일에서 이상하게 보여서 다시 손댄 UI들. 이게 다 실제로 겪은 문제들이에요.$n$) WHERE id = 'portfolio-admin-journey';
UPDATE blog_posts SET content_en = replace(content_en, $o$My first instinct was to separate data into JSON files. But that still meant opening files manually — it just moved the problem.
$o$, $n$My first instinct was to separate data into JSON files. But that still meant opening files manually. It just moved the problem somewhere else.$n$) WHERE id = 'portfolio-admin-journey';
UPDATE blog_posts SET content_en = replace(content_en, $o$With RLS policies in place, public read worked fine but writes required an authenticated user. That meant I needed a UI for that authenticated user — which naturally led to an admin panel.
$o$, $n$With RLS policies in place, public read worked fine but writes required an authenticated user. That meant I needed a UI for that authenticated user, which naturally led to an admin panel.$n$) WHERE id = 'portfolio-admin-journey';
UPDATE blog_posts SET content_en = replace(content_en, $o$**A shared tech icon module** emerged from a real bug. Three different sections (project detail, blog detail, about) were each managing their own icon maps, and things were falling through the cracks — `GitHub`, `Netlify`, `Tailwind CSS v4` were all showing as plain text badges. I consolidated everything into a single `resolveIcon()` function that also strips version suffixes.
$o$, $n$**A shared tech icon module** emerged from a real bug. Three different sections (project detail, blog detail, about) were each managing their own icon maps, and things were falling through the cracks. `GitHub`, `Netlify`, and `Tailwind CSS v4` were all showing up as plain text badges. I consolidated everything into a single `resolveIcon()` function that also strips version suffixes.$n$) WHERE id = 'portfolio-admin-journey';
UPDATE blog_posts SET content_en = replace(content_en, $o$The portfolio became a small CMS. Far from the "just a link on my resume" I started with — but I think the process itself became the portfolio.
$o$, $n$The portfolio became a small CMS. It's a long way from the "just a link on my resume" I started with, but I think the process itself became the portfolio.$n$) WHERE id = 'portfolio-admin-journey';
UPDATE blog_posts SET content_en = replace(content_en, $o$Every piece of new code, every design decision that needed revisiting, every UI that looked wrong on mobile — those were all real problems I actually solved.
$o$, $n$Every piece of new code, every design decision that needed revisiting, every UI that looked wrong on mobile. Those were all real problems I actually solved.$n$) WHERE id = 'portfolio-admin-journey';
UPDATE blog_posts SET content_en = replace(content_en, $o$- Build output was a single chunk `index.js` at 2,647 KB — slow initial load$o$, $n$- Build output was a single 2,647 KB `index.js` chunk, so the initial load was slow$n$) WHERE id = 'react-page-refactoring';
UPDATE blog_posts SET content_en = replace(content_en, $o$File structure issues don't immediately affect functionality, making them easy to postpone — but they ultimately impact the entire team's velocity.$o$, $n$File structure issues don't immediately affect functionality, which makes them easy to postpone. But they ultimately slow down the whole team.$n$) WHERE id = 'react-page-refactoring';
UPDATE blog_posts SET content_en = replace(content_en, $o$Code splitting isn't a one-line config change — it's about changing the import approach itself. If the structure isn't organized first, it's hard to even determine where to apply lazy imports.$o$, $n$Code splitting isn't a one-line config change. It means changing how you import things in the first place. If the structure isn't organized first, it's hard to even tell where lazy imports belong.$n$) WHERE id = 'react-page-refactoring';
UPDATE blog_posts SET title_ko = replace(title_ko, $o$API 응답 형식 불일치와 useMemo 크래시 — undefined는 조용히 퍼져요$o$, $n$API 응답 형식이 어긋나 터진 useMemo, undefined는 조용히 퍼져요$n$) WHERE id = 'api-mismatch-usememo-crash';
UPDATE blog_posts SET title_en = replace(title_en, $o$API Response Mismatch and useMemo Crash — undefined Spreads Silently$o$, $n$How an API Response Mismatch Crashed useMemo, and Why undefined Spreads Silently$n$) WHERE id = 'api-mismatch-usememo-crash';
UPDATE blog_posts SET content_ko = replace(content_ko, $o$# API 응답 형식 불일치와 useMemo 크래시 — undefined는 조용히 퍼져요$o$, $n$# API 응답 형식이 어긋나 터진 useMemo, undefined는 조용히 퍼져요$n$) WHERE id = 'api-mismatch-usememo-crash';
UPDATE blog_posts SET content_en = replace(content_en, $o$# API Response Mismatch and useMemo Crash — undefined Spreads Silently$o$, $n$# How an API Response Mismatch Crashed useMemo, and Why undefined Spreads Silently$n$) WHERE id = 'api-mismatch-usememo-crash';
UPDATE blog_posts SET content_en = replace(content_en, $o$`response.data.content` is `undefined` because arrays don't have a `content` property. That `undefined` got stored in state, `useMemo` received it and tried calling `.filter()` — crash.$o$, $n$`response.data.content` is `undefined` because arrays don't have a `content` property. That `undefined` got stored in state, `useMemo` received it and tried calling `.filter()`, and it crashed.$n$) WHERE id = 'api-mismatch-usememo-crash';
UPDATE blog_posts SET content_en = replace(content_en, $o$The error message alone didn't make it obvious where `undefined` came from. `useMemo` wasn't calling the API directly — it received state from somewhere upstream.$o$, $n$The error message alone didn't make it obvious where `undefined` came from. `useMemo` wasn't calling the API directly. It received state from somewhere upstream.$n$) WHERE id = 'api-mismatch-usememo-crash';
UPDATE blog_posts SET content_en = replace(content_en, $o$That `undefined` got saved into `useState`, and during rendering, `useMemo` received it and tried calling `.filter()` — boom.$o$, $n$That `undefined` got saved into `useState`, and during rendering, `useMemo` received it and tried calling `.filter()`. Boom.$n$) WHERE id = 'api-mismatch-usememo-crash';
UPDATE blog_posts SET content_en = replace(content_en, $o$`undefined` doesn't throw immediately. It gets quietly stored in state, passes through multiple components, and explodes at the furthest point downstream. The error location and the cause location are different — that's what makes it hard to trace.$o$, $n$`undefined` doesn't throw immediately. It gets quietly stored in state, passes through multiple components, and explodes at the furthest point downstream. The place where it fails and the place where it starts are different, and that's what makes it hard to trace.$n$) WHERE id = 'api-mismatch-usememo-crash';
UPDATE blog_posts SET content_ko = replace(content_ko, $o$### a. 아이콘 메타 데이터 — useIcon.ts$o$, $n$### a. 아이콘 메타 데이터 (useIcon.ts)$n$) WHERE id = 'icon-system-implementation';
UPDATE blog_posts SET content_ko = replace(content_ko, $o$### b. 전역 아이콘 컴포넌트 — AppIcon$o$, $n$### b. 전역 아이콘 컴포넌트 (AppIcon)$n$) WHERE id = 'icon-system-implementation';
UPDATE blog_posts SET content_en = replace(content_en, $o$### a. Icon Metadata — useIcon.ts$o$, $n$### a. Icon Metadata (useIcon.ts)$n$) WHERE id = 'icon-system-implementation';
UPDATE blog_posts SET content_en = replace(content_en, $o$### b. Global Icon Component — AppIcon$o$, $n$### b. Global Icon Component (AppIcon)$n$) WHERE id = 'icon-system-implementation';
UPDATE blog_posts SET title_ko = replace(title_ko, $o$숨겨진 div의 역습 — React에서 hidden 클래스는 조건부 렌더링이 아니에요$o$, $n$숨겨진 div의 역습, React에서 hidden 클래스는 조건부 렌더링이 아니에요$n$) WHERE id = 'hidden-div-react-rendering';
UPDATE blog_posts SET title_en = replace(title_en, $o$The Hidden Div Strike Back — CSS hidden Is Not Conditional Rendering in React$o$, $n$The Hidden Div Strikes Back, or Why CSS hidden Isn't Conditional Rendering in React$n$) WHERE id = 'hidden-div-react-rendering';
UPDATE blog_posts SET content_ko = replace(content_ko, $o$# 숨겨진 div의 역습 — React에서 hidden 클래스는 조건부 렌더링이 아니에요$o$, $n$# 숨겨진 div의 역습, React에서 hidden 클래스는 조건부 렌더링이 아니에요$n$) WHERE id = 'hidden-div-react-rendering';
UPDATE blog_posts SET content_en = replace(content_en, $o$# The Hidden Div Strike Back — CSS hidden Is Not Conditional Rendering in React$o$, $n$# The Hidden Div Strikes Back, or Why CSS hidden Isn't Conditional Rendering in React$n$) WHERE id = 'hidden-div-react-rendering';
UPDATE blog_posts SET content_en = replace(content_en, $o$At first I wondered if the class name was the issue. I thought Tailwind's `hidden` (`display: none !important`) might behave differently — but however CSS hides something, it's unrelated to JS execution.$o$, $n$At first I wondered if the class name was the issue. I thought Tailwind's `hidden` (`display: none !important`) might behave differently. But no matter how CSS hides something, it has nothing to do with whether JS runs.$n$) WHERE id = 'hidden-div-react-rendering';
UPDATE blog_posts SET content_en = replace(content_en, $o$With conditional rendering, components unmount and remount on tab switches — meaning internal state resets. If you need to preserve state between tabs, two options:$o$, $n$With conditional rendering, components unmount and remount on every tab switch, so their internal state resets. If you need to preserve state between tabs, there are two options:$n$) WHERE id = 'hidden-div-react-rendering';
UPDATE blog_posts SET content_en = replace(content_en, $o$When state preservation isn't important, conditional rendering performs better — heavy components don't mount unnecessarily.$o$, $n$When you don't need to preserve state, conditional rendering performs better because heavy components don't mount unnecessarily.$n$) WHERE id = 'hidden-div-react-rendering';
UPDATE blog_posts SET content_en = replace(content_en, $o$Hiding with CSS means "invisible." Conditional rendering means "non-existent." For performance-sensitive components, control existence — not just visibility.$o$, $n$Hiding with CSS means "invisible." Conditional rendering means "non-existent." For performance-sensitive components, control whether they exist, not just whether they're visible.$n$) WHERE id = 'hidden-div-react-rendering';
UPDATE blog_posts SET title_ko = replace(title_ko, $o$@media print과 CSS 레이어의 충돌 — 인쇄 헤더가 사라지지 않던 이유$o$, $n$인쇄할 때 헤더가 사라지지 않던 이유, @media print와 CSS 레이어의 충돌$n$) WHERE id = 'css-print-layer-conflict';
UPDATE blog_posts SET title_en = replace(title_en, $o$@media print vs CSS Layers Conflict — Why the Print Header Wouldn't Hide$o$, $n$Why the Print Header Wouldn't Hide: @media print vs CSS Layers$n$) WHERE id = 'css-print-layer-conflict';
UPDATE blog_posts SET content_ko = replace(content_ko, $o$# @media print과 CSS 레이어의 충돌 — 인쇄 헤더가 사라지지 않던 이유$o$, $n$# 인쇄할 때 헤더가 사라지지 않던 이유, @media print와 CSS 레이어의 충돌$n$) WHERE id = 'css-print-layer-conflict';
UPDATE blog_posts SET content_en = replace(content_en, $o$# @media print vs CSS Layers Conflict — Why the Print Header Wouldn't Hide$o$, $n$# Why the Print Header Wouldn't Hide: @media print vs CSS Layers$n$) WHERE id = 'css-print-layer-conflict';
UPDATE blog_posts SET content_en = replace(content_en, $o$At first I thought it was a selector issue — spent a while checking if I needed a different selector than `.header`.$o$, $n$At first I thought it was a selector issue, and spent a while checking whether I needed something other than `.header`.$n$) WHERE id = 'css-print-layer-conflict';
UPDATE blog_posts SET content_en = replace(content_en, $o$Then I thought using `!important` inside `@media print` would work. There's actually a special reversal rule: `!important` inside a layer has higher priority than `!important` outside — the layer priority flips for `!important` declarations.$o$, $n$Then I thought using `!important` inside `@media print` would work. There's actually a special reversal rule: `!important` inside a layer has higher priority than `!important` outside it. For `!important` declarations, the layer priority flips.$n$) WHERE id = 'css-print-layer-conflict';
UPDATE blog_posts SET content_en = replace(content_en, $o$Layer declaration order matters — layers declared later have higher priority. Placing the `print` layer last lets print styles override other layers.$o$, $n$Layer declaration order matters. Layers declared later have higher priority. Placing the `print` layer last lets print styles override other layers.$n$) WHERE id = 'css-print-layer-conflict';
UPDATE blog_posts SET content_en = replace(content_en, $o$Styles that apply only in specific contexts — like print styles — need careful placement in the layer structure. Declaring them directly outside any layer, or placing a dedicated print layer last in the layer order, is the safe approach.$o$, $n$Styles that only apply in specific contexts, like print styles, need careful placement in the layer structure. Declaring them directly outside any layer, or placing a dedicated print layer last in the layer order, is the safe approach.$n$) WHERE id = 'css-print-layer-conflict';
UPDATE blog_posts SET content_ko = replace(content_ko, $o$### A. i18n 옵션 문자열 빌더 — useBuildOptionText$o$, $n$### A. i18n 옵션 문자열 빌더 (useBuildOptionText)$n$) WHERE id = 'common-utils-composable';
UPDATE blog_posts SET content_ko = replace(content_ko, $o$### B. 메뉴 권한 탐색 — useFindPermissionValue, useFindPermissionValueInput$o$, $n$### B. 메뉴 권한 탐색 (useFindPermissionValue, useFindPermissionValueInput)$n$) WHERE id = 'common-utils-composable';
UPDATE blog_posts SET content_ko = replace(content_ko, $o$### C. 파일 유형·용량 포맷 — useMimetypeCheck, useFileSizeFormat$o$, $n$### C. 파일 유형·용량 포맷 (useMimetypeCheck, useFileSizeFormat)$n$) WHERE id = 'common-utils-composable';
UPDATE blog_posts SET content_en = replace(content_en, $o$### A. i18n Option String Builder — useBuildOptionText$o$, $n$### A. i18n Option String Builder (useBuildOptionText)$n$) WHERE id = 'common-utils-composable';
UPDATE blog_posts SET content_en = replace(content_en, $o$### B. Menu Permission Search — useFindPermissionValue, useFindPermissionValueInput$o$, $n$### B. Menu Permission Search (useFindPermissionValue, useFindPermissionValueInput)$n$) WHERE id = 'common-utils-composable';
UPDATE blog_posts SET content_en = replace(content_en, $o$### C. File Type/Size Format — useMimetypeCheck, useFileSizeFormat$o$, $n$### C. File Type/Size Format (useMimetypeCheck, useFileSizeFormat)$n$) WHERE id = 'common-utils-composable';
UPDATE blog_posts SET content_ko = replace(content_ko, $o$### b. 공통 composable - useTable$o$, $n$### b. 공통 composable (useTable)$n$) WHERE id = 'table-component-structuring';
UPDATE blog_posts SET content_en = replace(content_en, $o$### b. Common Composable - useTable$o$, $n$### b. Common Composable (useTable)$n$) WHERE id = 'table-component-structuring';
UPDATE blog_posts SET content_ko = replace(content_ko, $o$### 1️⃣ 구조 재설계 — 독립형 상태 관리$o$, $n$### 1️⃣ 독립형 상태 관리로 구조 재설계$n$) WHERE id = 'filter-system-implementation';
UPDATE blog_posts SET content_en = replace(content_en, $o$### 1️⃣ Structural Redesign — Independent State Management$o$, $n$### 1️⃣ Redesigning the Structure Around Independent State$n$) WHERE id = 'filter-system-implementation';
UPDATE blog_posts SET content_ko = replace(content_ko, $o$### a. 초기 접근 – 단순 재귀 렌더링$o$, $n$### a. 처음 시도한 단순 재귀 렌더링$n$) WHERE id = 'tree-structure-management';
UPDATE blog_posts SET content_ko = replace(content_ko, $o$### c. 해결 전략 – 노드 상태 관리 + Lazy-loading 제어$o$, $n$### c. 노드 상태 관리와 Lazy-loading 제어로 해결$n$) WHERE id = 'tree-structure-management';
UPDATE blog_posts SET content_en = replace(content_en, $o$### a. Initial Approach – Simple Recursive Rendering$o$, $n$### a. Starting with Simple Recursive Rendering$n$) WHERE id = 'tree-structure-management';
UPDATE blog_posts SET content_en = replace(content_en, $o$### c. Solution Strategy – Node State Management + Lazy-loading Control$o$, $n$### c. Fixing It with Node State Management and Lazy-loading Control$n$) WHERE id = 'tree-structure-management';

-- 코드 예시 안의 주석
UPDATE blog_posts SET content_ko = replace(content_ko, $o${/* 단락 평가 — false면 아무것도 마운트되지 않음 */}$o$, $n${/* 단락 평가: false면 아무것도 마운트되지 않음 */}$n$) WHERE id = 'hidden-div-react-rendering';
UPDATE blog_posts SET content_en = replace(content_en, $o${/* Short-circuit — nothing mounts when false */}$o$, $n${/* Short-circuit: nothing mounts when false */}$n$) WHERE id = 'hidden-div-react-rendering';
UPDATE blog_posts SET content_ko = replace(content_ko, $o$/* @layer 밖 — 항상 우선순위 높음 */$o$, $n$/* @layer 밖: 항상 우선순위 높음 */$n$) WHERE id = 'css-print-layer-conflict';
UPDATE blog_posts SET content_ko = replace(content_ko, $o$/* @layer base 안 — 항상 우선순위 낮음 */$o$, $n$/* @layer base 안: 항상 우선순위 낮음 */$n$) WHERE id = 'css-print-layer-conflict';
UPDATE blog_posts SET content_ko = replace(content_ko, $o$/* 레이어 순서 선언 — 나중에 선언된 레이어가 우선순위 높음 */$o$, $n$/* 레이어 순서 선언: 나중에 선언된 레이어가 우선순위 높음 */$n$) WHERE id = 'css-print-layer-conflict';
UPDATE blog_posts SET content_en = replace(content_en, $o$/* Outside @layer — always higher priority */$o$, $n$/* Outside @layer: always higher priority */$n$) WHERE id = 'css-print-layer-conflict';
UPDATE blog_posts SET content_en = replace(content_en, $o$/* Inside @layer base — always lower priority */$o$, $n$/* Inside @layer base: always lower priority */$n$) WHERE id = 'css-print-layer-conflict';
UPDATE blog_posts SET content_en = replace(content_en, $o$/* Layer order declaration — later layers have higher priority */$o$, $n$/* Layer order declaration: later layers have higher priority */$n$) WHERE id = 'css-print-layer-conflict';

COMMIT;

-- 확인: 남은 줄표 개수 (0이어야 함. 코드 블록 안 기호는 제외 안 되므로 아래는 참고용)
SELECT id,
       (length(title_ko)   - length(replace(title_ko,   '—', ''))) AS title_ko_dash,
       (length(title_en)   - length(replace(title_en,   '—', ''))) AS title_en_dash,
       (length(content_ko) - length(replace(content_ko, '—', ''))) AS content_ko_dash,
       (length(content_en) - length(replace(content_en, '—', ''))) AS content_en_dash
FROM blog_posts
ORDER BY date DESC;
